### ISSUE TITLE
Alternative Python Library

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#1]
I found an alternative python wrapper for the NXT. Is it worth looking into?
[https://pypi.python.org/pypi/jaraco.nxt](https://pypi.python.org/pypi/jaraco.nxt)

**Comment by rowanborder** [comment]
Jaraco NXT relies on serial communication using pyserial instead of bluetooth library using pybluez. Therefore cannot be used to discover a specific bluetooth device.
