### ISSUE TITLE
Robot design: Steering rack concept

### ISSUE THREAD

**Issue by grantkelly** [Tasignotas/SDP#11]
Mac mentioned a steering system akin to a car's, in which the front wheels may be on some kind of partially rotating axle. The back wheels would be used for drive.

If a concept design could be produced and reviewed by the team this could be a good. 

It should be noted that other teams are also investigating this design. Their design features a horizontally spinning cog that rotates through 30 degrees, with the motor driving the front wheels by means of a vertical rod, which rotates to spin the wheels.

Rear-wheel-drive should make it easier to angle the robot quickly. Front-wheel-drive should allow better pinpoint steering control, but the turning circle would be horrible.

**Comment by easyCZ** [comment]
I assume this is no longer in question. If I am wrong, please re-open.
