### ISSUE TITLE
Test: Single Bluetooth Dongle Communication with both Bricks

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#13]
Research and test how communication with both Bricks from a single computer will work. Control of the robots might have to be turned into threaded  processes.

**Comment by rowanborder** [comment]
Stackoverflow on communicating with multiple NXT Bricks from one computer.
http://bricks.stackexchange.com/questions/1195/can-i-control-2-nxt-bricks-from-a-computer-using-bluetooth-at-the-same-time
Seems like communicating with multiple bluetooth devices at the same time depends on the drivers being used.
NXTs do have a master-slave functionality but not sure if this can be used with Python.

**Comment by Tasignotas** [comment]
It's actually easier than it looks. Milan and I managed to control both bricks just by making two connections, for example:

connection_D = Connection(name='GRP7D')
BRICK_D = connection.brick
connection_A = Connection(name='GRP7A')
BRICK_A = connection.brick

So, I'm closing this one.
