### ISSUE TITLE
Codec Issue: Testing CV using Recorded Video

### ISSUE THREAD

**Issue by rowanborder** [Tasignotas/SDP#14]
The codec used to record the video files on the DICE machines seems to be unreadable by OpenCV Python (at least on Windows). They may need to be converted to another codec.

**Comment by macwai1** [comment]
I seem to be having the same problem on my Mac.

**Comment by rowanborder** [comment]
I will try re-recording or converting the video this afternoon.

**Comment by rowanborder** [comment]
The issue is compiling OpenCV without ffmpeg support. It was easier to convert the videos to image sets in the img folder than to recompile OpenCV with ffmpeg.
