### ISSUE TITLE
Vision/Sensors: Robot Orientation

### ISSUE THREAD

**Issue by rowanborder** [Tasignotas/SDP#15]
We need to know with accuracy the orientation of the robots on the pitch for catching, passing and shooting the ball. This could either be done using accurate computer vision or an on-board compass sensor. We should investigate the relative merits of both approaches.

**Comment by rowanborder** [comment]
We also need to capture a movement vector for the ball so that our robots can block/catch the ball at an appropriate angle.

**Comment by easyCZ** [comment]
Frame to frame analysis should help with this

**Comment by easyCZ** [comment]
Closed until the possible change of the shape of the plate is resolved.
