### ISSUE TITLE
Vision: Ball Possession Boolean

### ISSUE THREAD

**Issue by rowanborder** [Tasignotas/SDP#18]
A boolean value representing whether a robot R has possession of the ball B. Possibly by using some proximity and orientation calculations with the vision?

**Comment by macwai1** [comment]
An ultrasonic sensor at the kicker should be simpler, I guess?

**Comment by rowanborder** [comment]
Andrius said that the ultrasonic sensor isn't accurate at distances of less
than 8 cm so it might get confused with the walls. A color sensor could
work though possibly. Can someone investigate?

**Comment by easyCZ** [comment]
This should be a planner issue.

**Comment by easyCZ** [comment]
Could you please elaborate on how you image this to work? I assumed the planner would calculate the distance of the ball from the robot (and direction) and determine the location from there. Or do you mean ball possession on a zone basis? - We have the ball vs opponent has the ball. Thanks.
