### ISSUE TITLE
Pitch and zone selection

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#21]
I wrote a little GUI app that lets the user create polygons for the whole field and each zone. Points are saved into json and can be retrieved by other apps. Some testing of how well it works and what functionality is expected and isn't availabale would be good.

Each selection should be terminated by pressing 'q'. Please follow instructions printed to the terminal. To run, do _python configure.py_

**Comment by rowanborder** [comment]
This will be really useful for calibrating the pitch and zones for the planning!

**Comment by easyCZ** [comment]
Closed for now. If you feel like some other features are needed, please re-open.
