### ISSUE TITLE
Fast object detection

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#22]
Together with Mac and Maneshka we found a very fast way to detect the robots on the field based on masking and contour recognition. I presume it will work on the ball too.

A way to determine the front of the robot is required as the T is almost evenly sized and elliptical masking does not help. I will refactor the code later and show the issue. It would be nice if we could get other ideas how to determine the orientation with maximum precision.

One failed approach was to find maximum left, top, right and bottom values and use pixel distance to determine the orientation. Almost even sizing of the T makes this a failed attempt. 

The question is, given a binary image with an evenly sized T shape, how do you determine which is the top. I can find majority of pixels inside the T, draw a bounding box or fit an ellipse over it but with limited precision and high volatility to camera distortion.

All ideas are welcome.

**Comment by rowanborder** [comment]
If a vision solution cannot be found that can detect robot orientation with speed and precision I would like to propose that we use the NXT compass sensor which has an accuracy of 1 degree and can be read at least every 100ms.

**Comment by easyCZ** [comment]
Closing for now. The shapes might change to the School of Informatics lower case **i** logo. For now we should incorporate location tracking with dummy speed & orientation and focus on multiprocessing.
