### ISSUE TITLE
Vision: differences in video stream

### ISSUE THREAD

**Issue by victor-dumitrescu** [Tasignotas/SDP#23]
The left and the right images are both the results of the same code but running on DICE machines which get the video from different amplifiers. (At least that's the only explanation I could come up with.) We need a way to deal with these variations.
![s2](https://f.cloud.github.com/assets/1386428/2015562/760f420e-87bd-11e3-9cc1-c0e3f7debaf1.png)

**Comment by easyCZ** [comment]
If we discover this being a general case, we should report it to Garry. For now closing as there is nothing we can do without knowing specific computers with this issue.
