### ISSUE TITLE
Vision: Add Multiprocessing to Trackers

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#25]
Make each Tracker run in a separate process.

**Comment by easyCZ** [comment]
Implemented. Closing for now unless bugs come up.

**Comment by rowanborder** [comment]
Is there a function implemented yet which will pass the position vectors to
the planning system?

**Comment by easyCZ** [comment]
It's commented out for now. Will enable it in a second.

**Comment by easyCZ** [comment]
The vision now passes the coordinates into the planner. The mocked planner function is in planner.py under Planner object. For now the angle and speed are mocked but it's coming. Probably tomorrow around lunch time.
