### ISSUE TITLE
Running code from the brick only

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#3]
We might need to run the code from the brick only. For that we might have to turn to LeJOS - Java implementation of the NXC language. It would be useful to have a look at it and try to build some code and test it, in case we do end up having to run it from the brick only. [LeJOS](http://www.lejos.org/)

**Comment by rowanborder** [comment]
Ask Garry about these constraints given that we are using Python.

**Comment by easyCZ** [comment]
Garry said that for the milestone we can use the vision as well as code running on the dice. One added benefit is, they have installed nxt-python and bluez so that we do not need a virtual machine and can actually control it from dice.

**Comment by rowanborder** [comment]
Have you confirmed its working on DICE?

**Comment by easyCZ** [comment]
Yes. They will deploy it to all the dice tomorrow.
