### ISSUE TITLE
Vision: Kalman filter only works for constant speed/acceleration

### ISSUE THREAD

**Issue by victor-dumitrescu** [Tasignotas/SDP#31]
This means that it can only be used on the segments where the ball is not bouncing off the walls. It can accurately predict the position of the ball is we momentarily lose track of it, but it must be reset every time the ball stops to move in a continuous motion.
These are some examples of how the Kalman filter performs in these scenarios:
![figure_1](https://f.cloud.github.com/assets/1386428/2104966/10348c14-8f83-11e3-8436-e5de6b5aaaa8.png)
![figure_2](https://f.cloud.github.com/assets/1386428/2104967/15326056-8f83-11e3-8a1c-89f9bf120973.png)

This means that using the filter depends on accurately measuring the direction and velocity of the ball.

**Comment by easyCZ** [comment]
Good work. I think this could work. We can try to improve the ball tracking and see if the filter helps us. Wanna look into it tomorrow?

**Comment by easyCZ** [comment]
Closing for now. We should not need to use it in the vision system.
