### ISSUE TITLE
VISION - PLANNER: Angle 

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#37]
What units and which relative vector is the angle to be computed? We talked about switching to radians. Can you please specify which units you are expecting?

**Comment by rowanborder** [comment]
Radians please in polar coordinates. I.e. positive x axis is 0, positive y axis is pi/2, negative x axis is pi

From: Milan Pavlik
Sent: ‎Monday‎, ‎February‎ ‎10‎, ‎2014 ‎12‎:‎43‎ ‎PM
To: Tasignotas/SDP

What units and which relative vector is the angle to be computed? We talked about switching to radians. Can you please specify which units you are expecting?
