### ISSUE TITLE
VISION: Background Subtraction

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#39]
Investigate the method of background subtraction and how it could be used to improve our vision accuracy.

**Comment by easyCZ** [comment]
For samples, have a look at [this](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_video/py_bg_subtraction/py_bg_subtraction.html#background-subtraction)

**Comment by macwai1** [comment]
I can look into this.

**Comment by macwai1** [comment]
I'm facing problems in the background subtraction modules in cv2. Apparently it isn's there and we have to update our opencv to opencv's master branch. Tried it but we're required to also update cmake and that requires group access. Any thoughts?
http://stackoverflow.com/questions/18721552/opencv2-python-createbackgroundsubtractor-module-not-found

**Comment by easyCZ** [comment]
Whats the exact function you're trying to call?

**Comment by victor-dumitrescu** [comment]
If you can't get OpenCV to work, have a look at SimpleCV. I haven't explored it too deeply, but I was able to do background subtraction by simply using '-'. http://tutorial.simplecv.org/en/latest/examples/image-math.html

You can try to install SimpleCV with the script in the repo (install_simplecv.sh).

**Comment by macwai1** [comment]
Any of the following:
cv2.createBackgroundSubtractorMOG()
cv2.createBackgroundSubtractorMOG2()
cv2.createBackgroundSubtractorGMG()
As shown in the link which you've posted.

**Comment by macwai1** [comment]
SimpleCV looks promising. I'll see what it can do alongside the background subtraction technique.

**Comment by macwai1** [comment]
Background Subtraction with opencv seems accurate, especially for detecting red ball and plates.

![screenshot](https://f.cloud.github.com/assets/5704679/2195654/3983cf70-98a3-11e3-8875-20a184432639.png)

**Comment by macwai1** [comment]
Even after doing background subtraction, we still might have to apply maskings to differentiate the objects on the pitch, don't we? Does this lead us back to the beginning?

**Comment by macwai1** [comment]
Looks like background subtraction is very reliable and versatile. Below is a screenshot of a test I did on the second pitch. The results are similar than that of the first pitch. :dancers: 
![snapshot2](https://f.cloud.github.com/assets/5704679/2230219/b3cad2ae-9afd-11e3-8a33-ac3e8a2f1de9.png)

**Comment by easyCZ** [comment]
Looks good!

**Comment by easyCZ** [comment]
Works very well. Will be added today.
