### ISSUE TITLE
VISION: Distortion

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#41]
Investigate methods to remove camera distortion. Good starting point is [here](https://opencv-python-tutroals.readthedocs.org/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html#calibration)

**Comment by easyCZ** [comment]
Can we get an update on this? @grantkelly

**Comment by easyCZ** [comment]
Could we finally get an update on this?

**Comment by macwai1** [comment]
Tried this, seemed pretty expensive with about a 0.4 second delay. It couldn't detect the corners of the pitch so I placed a chessboard on the pitch. Don't think it's reliable as it can fail to detect the corners often.

**Comment by easyCZ** [comment]
Is it not something you pre-calibrate and keep the values and simply apply
to all future images?

**Comment by victor-dumitrescu** [comment]
Mostly done with radial distortion. Might require some refactoring and perhaps using more sample images.
