### ISSUE TITLE
PLANNER: Refactor code in planning and add unit tests

### ISSUE THREAD

**Issue by Tasignotas** [Tasignotas/SDP#46]

**Comment by rowanborder** [comment]
I’ll start refactoring some of the shooting and path finding code and working on PID functions. If someone wants to write a basic (no gui) testing framework for the planner and planning functions?

From: Ignotas
Sent: ‎Friday‎, ‎February‎ ‎14‎, ‎2014 ‎4‎:‎49‎ ‎PM
To: Tasignotas/SDP

**Comment by easyCZ** [comment]
Each of those functions should be tested by the developer using unittest
package in python. There's no need to write a framework for it.

**Comment by Tasignotas** [comment]
Rowan, I put myself as an assignee to this task and have done some work already, so can I please finish this?

**Comment by rowanborder** [comment]
Sorry I didn't see that. Yes of course.

**Comment by easyCZ** [comment]
This seems to be complete. Re-open if I'm wrong.
