### ISSUE TITLE
PLANNER: PID Feedback Loop 

### ISSUE THREAD

**Issue by rowanborder** [Tasignotas/SDP#48]
Implement a PID Feedback System to calibrate displacement and rotation multipliers for the new robot design.

**Comment by easyCZ** [comment]
Unless we have the new robot we can't really do this, can we?

**Comment by rowanborder** [comment]
Given the results we've gotten so far it does seem unlikely that it we'll be able to effectively calibrate tacho units and distance, but even with the current robot we should calibrate time and distance at a certain power so we can make sure we don't run over boundaries and we can actually move to a point effectively.

**Comment by easyCZ** [comment]
Can we get an update on this? Thanks. @rowanborder

**Comment by rowanborder** [comment]
Working on this now.

**Comment by rowanborder** [comment]
We can discuss the usefulness/necessity for PID tomorrow.
