### ISSUE TITLE
SimpleCV Problem

### ISSUE THREAD

**Issue by macwai1** [Tasignotas/SDP#50]
I've gotten simpleCV to mostly work now after facing some problems:
1. Problem where /libs/lib/python2.6/site-packages/SimpleCV-1.3-py2.6.egg/SimpleCV/sampleimages/simplecv.png cannot be located.
   Solution: Simply make a sampleimages folder and find a simplecv.png image on google. Then paste it in.
2. NotImplementedError: font module not available
   (ImportError: libSDL_ttf-2.0.so.0: cannot open shared object file: No such file or directory)
   I've not solved this as libSDL_ttf-2.0.so.0 literally cannot be opened because it's shared(?)
   I ran the script install_simplecv.sh from the scripts folder. Must I run it in some other directory?

Thanks.
Mac

**Comment by easyCZ** [comment]
I've had the same issue with the font and the script has not helped me. Not sure how to fix the issue. Sorry.

**Comment by easyCZ** [comment]
I figured we're letting SimpleCV go atm.
