### ISSUE TITLE
VISION: Color Normalization

### ISSUE THREAD

**Issue by RyanrDavies** [Tasignotas/SDP#52]
Investigate algorithms for normalizing the colours to remove/reduce the effect of shadows and other factors on the vision system.

http://en.wikipedia.org/wiki/Color_normalization lists several algorithms whcih may be useful.

**Comment by easyCZ** [comment]
Using [this](http://docs.opencv.org/modules/imgproc/doc/histograms.html?highlight=equalizehist#equalizehist) is proposed by several posts on the internet.

**Comment by RyanrDavies** [comment]
I've experimented a bit with the equalizeHist method. It does sometimes help to distinguish colours, but I found it also tends to introduce a large amount of noise to the image.

**Comment by easyCZ** [comment]
Would a slight blur help before normalizing?

**Comment by RyanrDavies** [comment]
Possibly. I'll give it a shot tomorrow.

**Comment by RyanrDavies** [comment]
A slight blur helps a bit. Most of the noise is in the background, so it may be useful in addition to background subtraction?

**Comment by easyCZ** [comment]
Working well with color subtraction. Will be included in today's addition of features to the GUI. Good job!

**Comment by easyCZ** [comment]
@RyanrDavies, could you please look over my code and see why the normalization is acting weird? It is in `preprocessing/preprocessing.py` _line 46_

Thanks!
![normalize](https://f.cloud.github.com/assets/1419286/2240822/3e3cb1a2-9caf-11e3-9759-1a7c7945646d.png)

**Comment by easyCZ** [comment]
Somewhat fixed it but still getting white instead of the red color for the ball.

**Comment by RyanrDavies** [comment]
the line:

```
   frame[:, :, 1] = cv2.equalizeHist(frame[:, :, :1])
```

should be:

```
     frame[:, :, 1] = cv2.equalizeHist(frame[:, :, 1])
```

but apart from that I can't see anything else different.

**Comment by easyCZ** [comment]
Thanks, that solved it.
