### ISSUE TITLE
CONTROLLER: Robot Control

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#54]
Re-implement command execution in `controller.py` to make use of the new communication API. Ask Rowan for info on the comms API if unclear.

**Comment by rowanborder** [comment]
Code to communicate with the Arduino over wireless will be something like the following:

import serial
comm_port = '/dev/ttyUSB<port_number>'
arduino_comm = serial.Serial(comm_port, 9600, timeout=1)
arduino_comm.write('<robot_command_string>\n')

The communication API is as follows:

SET_ENGINE_ATTACKER <MAX_SPEED_LEFT_STEPPER> <ACCELERATION_LEFT_STEPPER> <MAX_SPEED_RIGHT_STEPPER> <ACCELERATION_RIGHT_STEPPER>

SET_ENGINE_DEFENDER <MAX_SPEED_LEFT_STEPPER> <ACCELERATION_LEFT_STEPPER> <MAX_SPEED_RIGHT_STEPPER> <ACCELERATION_RIGHT_STEPPER>

RUN_ENGINE_ATTACKER <LEFT_STEPPER_STEPS> <RIGHT_STEPPER_STEPS>

RUN_ENGINE_DEFENDER <LEFT_STEPPER_STEPS> <RIGHT_STEPPER_STEPS>

RUN_KICKER_ATTACKER <POSITION>

RUN_KICKER_DEFENDER <POSITION>

RUN_ CATCHER_ATTACKER <POSITION>

RUN_CATCHER_DEFENDER <POSITION>

MAX_SPEED: Value between 50 and 1000 in Steps Per Second

ACCELERATION: Value between 50 and 1000 in Steps Per Second

STEPS: Number of steps to move the stepper motor. Negative values move the stepper motor in reverse. There are 48 steps per revolution of the stepper motor.

POSITION: Position to move the servos to in degrees (0-180)

Values for command parameters are validated by the Arduino before execution. Invalid commands will return ‘Invalid Command String’ over wireless to the serial port. 

Calibration of steps to distance travelled will be achieved using the PID Feedback Loop.

From: Milan Pavlik
Sent: ‎Sunday‎, ‎February‎ ‎23‎, ‎2014 ‎1‎:‎33‎ ‎PM
To: Tasignotas/SDP

Re-implement command execution in controller.py to make use of the new communication API. Ask Rowan for info on the comms API if unclear.
