### ISSUE TITLE
PLANNING: Ball possession

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#63]
Determine whether a robot is likely to have grabbed the ball. This can be done by using the locations of ball and robot and the angle. Ideally, we'd keep track of this information between frames and re-calculate the probability the robot has to ball between frames. This would be done by knowing the last location and new location, if the new location has changed, calculate the vector change and check that the ball has moved in the same vector.

This may be unreliable in stationary positions but it would give us additional information. Especially when the robots are rotating.

**Comment by Tasignotas** [comment]
Might look into this if we decide that the ball possession using the catcher area is not reliable.
