### ISSUE TITLE
VISION: Perspective Distortion

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#68]
We could try this:
![3tsyq](https://f.cloud.github.com/assets/1419286/2341055/30b63a70-a4d0-11e3-9f34-190ff0e32596.png)

**Comment by victor-dumitrescu** [comment]
Barrel distortion is actually a type of radial distortion ("The presence of the radial distortion manifests in form of the “barrel” or “fish-eye” effect."), which we already have. What we need is perspective distortion (http://en.wikipedia.org/wiki/Perspective_projection_distortion). As far as I understood, it can be solved by marking a perimeter of points on the image and mapping them to the shape that they have in the actual plane. This function gets the transform: http://docs.opencv.org/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#Mat findHomography(InputArray srcPoints, InputArray dstPoints, int method, double ransacReprojThreshold, OutputArray mask). 

I also remember reading something about doing this using the camera matrix (which we already have) and the distance from the camera to the plane, but I can't seem to find the article right now. I might be mistaken.

For reference:
http://comments.gmane.org/gmane.comp.lib.opencv/7454

**Comment by easyCZ** [comment]
@victor-dumitrescu , when do you think this could be ready?

**Comment by victor-dumitrescu** [comment]
I'm heading towards AT soon and I'll start working on it. If I understood everything right, it should be ready by tomorrow.

**Comment by victor-dumitrescu** [comment]
I implemented this and as far as I can see the system now uses the adjusted coordinates. They are also displayed in the GUI, instead of the raw values.

I haven't managed to figure out how the grabber positions are being calculated, but I guess they don't rely on the locate() function from the vision system, because the positions returned by those functions are being adjusted. I'll figure it out tomorrow.

**Comment by victor-dumitrescu** [comment]
Fixed grabbers, ignore previous comment (I was forgetting to correct some points).

**Comment by easyCZ** [comment]
Good work! I'll test it tomorrow :)
