### ISSUE TITLE
COMM: Faster write to serial

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#69]
I was wondering if shortening the command message could lead to faster writes on the serial port? @rowanborder

**Comment by rowanborder** [comment]
Looks like Serial.write() in pyserial is block by default:

"Writes are blocking by default, unless writeTimeout is set. For possible values refer to the list for timeout above." -  http://pyserial.sourceforge.net/pyserial_api.html

We should try using the writeTimeout = 0 parameter to solve this. The only disadvantage is that we won't get an error returned if there is a problem sending the serial command.

**Comment by easyCZ** [comment]
Regardless of that, wouldn't sending just 'E 10 10 10 10' on a separate port be enough to send the message to the robot? I'm concerned about the size of the message and I'm not sure if we can directly control the number of bits we send.

**Comment by easyCZ** [comment]
Also, we might actually want to have it blocking. The reason for this is we produce messages to be sent faster then they actually get written through the I/O and it will build up a Queue the same way it did when I made it multi-processed. The robots then run around executing old commands and all goes to disarray.

**Comment by rowanborder** [comment]
Well the current serial data rate is set to 9600 baud (9600 bits per second) so 1200 bytes per second. Our longest command so far is 'D_RUN_ENGINE -1000 -1000\n', so thats 25 bytes of data being sent which should therefore transmit in 21ms. If we reduced the command to 'DE -1000 -1000\n' then thats 15 bytes that should transmit in 12ms. But the Xbee modules can support transmission rates of up to 115200 bits per second (which would send 25 bytes in 2ms). The only concern there is that the data might not be read from the Arduino serial buffer (64 bytes) fast enough to prevent overflow. This depends on the execution time of the main control loop on the Arduino which determines frequency of the Arduino clock. Given that it would take 4ms to send 64 bytes that would mean we only need to have a clock frequency better than 250Hz. The Arduino is rated to 16MHz so we should be fine!

**Comment by Tasignotas** [comment]
Haha, like the calculations! You think you could try this anytime soon?

**Comment by rowanborder** [comment]
I have a tutorial tomorrow at 11 but can come to AT at 12 and try stuff out

**Comment by easyCZ** [comment]
Sounds great, thanks!

**Comment by rowanborder** [comment]
Testing sending commands strings continuously to Arduino over Xbee and reading the received data to verifying integrity at 115200bps. Seems to work fine and doesnt cause command corruption. Need to verify with live tests.

**Comment by easyCZ** [comment]
@rowanborder, Have you had a chance to very with live tests?

**Comment by rowanborder** [comment]
Not yet I’m getting CS done today. Ill try some live testing tmr.

From: Milan Pavlik
Sent: ‎Sunday‎, ‎March‎ ‎9‎, ‎2014 ‎1‎:‎36‎ ‎PM
To: Tasignotas/SDP
Cc: rowanjborder@gmail.com

@rowanborder, Have you had a chance to very with live tests?
