### ISSUE TITLE
Driving: One sensor, One Sided Turns

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#7]
Optimize code and have a robot that can safely drive inside the field (attack and defence). No vision for now.

**Comment by rowanborder** [comment]
Need to work on movement esp. turning. Replace variable power turns with
turns using tacho units for accuracy and on the spot turns. I have built a
movement class that I will test tonight.

**Comment by easyCZ** [comment]
At the moment, the robot is capable of driving inside the field okay. We might have to do more testing to tweak turning.

As of the email we received, the next step is to make it figure out if has made a full circle and stop where it first turned. Using SynchronizedMotor and tacho_units could help. 

We could make it work with this concept:
If we run straight for longer than some threshold, then we are probably running alongside the line. Count the number of turns made and if greater than some threshold, mark it as a 'proper' turn, otherwise mark it as 'minor' turn. Once we make 4(?) turns, we retrieve the "time" we ran forward initially and figure out how far we need to run. This is all without the vision.

Alternatively, design a vector unit system that can keep track of the movement/rotation. Add all the actions made together and we end up with a single vector pointing in the direction of the final move.

Getting this done will make us pass the first milestone even without the vision.

**Comment by easyCZ** [comment]
@Tasignotas managed to get the robot finish in the same position it started in by timing ee476b95506d532cd75d1bbf4fb6c8e3829a7e67. All that remains to complete the milestone is to time the defender pitch and store in the code. It's hacky but works surprisingly well.
