### ISSUE TITLE
COMM: Robots on different ports

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#70]
Ignotas brought this up today, do you think we could have the robots on different ports to  stop both robots receiving both signals?

**Comment by rowanborder** [comment]
Looks like we can update the firmware on the Xbee from 802.15.4 to DigiMesh which allows us to set an individual address for each Xbee and communicate with an Xbee with a specific address using a special API mode.

http://examples.digi.com/get-started/configuring-xbee-radios-with-x-ctu/

https://pypi.python.org/pypi/XBee

http://stackoverflow.com/questions/13436471/how-can-i-send-strings-of-data-to-an-xbee-with-a-python-library

**Comment by easyCZ** [comment]
Looks promising, let me know if you need any help.

**Comment by rowanborder** [comment]
Had problems getting this working. Xbee firmware has to be set to a special API mode to allowing specifying a destination address. Works initially but receiving data fails after ~108 bytes, Could be an issue with the firmware settings or an issue with the python library for the Xbee API. I can look into these problems further but an increase to a baudrate of 115200bps should resolve our latency issues and any bottleneck is unlikely to be on the Arduino receiving side.
