### ISSUE TITLE
Servo motor feedback

### ISSUE THREAD

**Issue by macwai1** [Tasignotas/SDP#75]
Rowan, is it possible if the Arduino can give us some kind of feedback if the grabber is currently extended or retracted? It may be quite useful as the planner will be less prone to bugs.

**Comment by rowanborder** [comment]
This would involve having a serial read command in the controller that passes a value directly to the planner but it could be implemented. Should talk to @tasignotas about that. But from the Arduino side yes its entirely possible.

From: macwai1
Sent: ‎Saturday‎, ‎March‎ ‎8‎, ‎2014 ‎10‎:‎49‎ ‎AM
To: Tasignotas/SDP

Rowan, is it possible if the Arduino can give us some kind of feedback if the grabber is currently extended or retracted? It may be quite useful as the planner will be less prone to bugs.

**Comment by easyCZ** [comment]
This could also be done from the vision. It might be tricky but waiting for serial response from the robot is not desirable for reasons of speed.

**Comment by easyCZ** [comment]
We have agreed to leave this to the planner for the moment. If the FSMs are designed carefully then no vision/servo feedback is needed.
