### ISSUE TITLE
VISION: Test perspective distortion

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#81]
@victor-dumitrescu has implemented the perspective distortion, we need to test it and see how reliable it is to provide feedback for Victor in case changes are needed. This could be done without the comms by simply having the robot there and move it closer.

Set up: In the defender zone, make the robot point to the wall perpendicular to its zone. Align the ball perfectly and take note of the actions returned. Ideally, the planner would return only move forward actions.

**Comment by macwai1** [comment]
Don't know if it's just me but the bounding box on the plates looks quite off.

**Comment by easyCZ** [comment]
Shouldn't that be the point of the perspective fix?

**Comment by victor-dumitrescu** [comment]
They're supposed to be off. But it might also be the case that the parameters need tweaking or I got something wrong. I'll be in AT soon.

**Comment by easyCZ** [comment]
Works amazing. Good job!
