### ISSUE TITLE
PLANNING: Dynamic Target Selection

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#84]
Make the Attacker robot dynamically pick the place of the goal to shoot into. This would be implemented in the DefaultAttackerAttack strategy. Later we can provide a more fine grained level of Attack strategies.

**Comment by Tasignotas** [comment]
I think that we should leave the "DefaultAttackerAttack" class as it is and create a new class which implements an attacker that has dynamic aiming.

**Comment by easyCZ** [comment]
Sounds good.
