### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by easyCZ** [Tasignotas/SDP#96]
Start working on the final presentation. A shared google docs document would be good.

I think the following sections could be included:
Intro
- Main project ideas

Main
- Robot design
- Vision
- Planning (not too detailed as we don't want to reveal everything)
- Obstacles encountered
- Solutions

Any other ideas?

**Comment by RyanrDavies** [comment]
I went to the sdp presentation skills lecture today. Key points:
- Probably 10 to 15 slides
- Probably only one or two people to present
- Questions should be answered by the person in the group who is most qualified to answer
- It's better to cover a small number of points in detail, than a large number of points briefly

Also, we need to sign up for a practice slot on Thursday.
